### PR TITLE
[bn] Localize loosely-coupled-architecture.md

### PR DESCRIPTION
**Pull request by Arindam200**
Signed-off-by: Arindam Majumder [arindammajumder2020@gmail.com](mailto:arindammajumder2020@gmail.com)
Localizes `loosely-coupled-architecture.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

### CODE REVIEW

**Review by mitul3737 — APPROVED** [review]
Lgtm

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by Imtiaz1234** [comment]
haha! This file looks good but can not be merged. Haha.. Kindly correct the branching.

**Comment by mitul3737** [comment]
You have to correct this branchings 
image

**Comment by Arindam200** [comment]
> Signed-off-by: Arindam Majumder [arindammajumder2020@gmail.com](mailto:arindammajumder2020@gmail.com) Localizes `loosely-coupled-architecture.md` to Bengali This is an initial PR as may need some improvements! Tracking issue: [cncf#410](https://github.com/cncf/glossary/issues/410)

I have changed the branch and made another PR! Please check that!

**Pull request merged**
